kind: pipeline
type: docker
name: hx_linux_amd64

environment:
  GOOS: linux
  GOARCH: amd64
  CGO_ENABLED: 0
  GO111MODULE: on

steps:
  - name: restore-cache
    image: drillster/drone-volume-cache
    pull: always
    volumes:
      - name: cache
        path: /cache
    settings:
      restore: true
      mount:
        - go_cache/GOPATH
        - go_cache/GOCACHE

  - name: build
    image: golang:1.19
    pull: if-not-exists
    environment:
      GOCACHE: /drone/src/go_cache/GOCACHE
      GOPATH: /drone/src/go_cache/GOPATH
      GOMODCACHE: /drone/src/go_cache/GOPATH/pkg/mod
      GOBIN: /drone/src/go_cache/GOPATH/bin
    commands:
      - pwd
      - export PATH=$PATH:$GOBIN
      - make build

  - name: rebuild-cache
    image: drillster/drone-volume-cache
    pull: if-not-exists
    volumes:
      - name: cache
        path: /cache
    settings:
      rebuild: true
      mount:
        - go_cache/GOPATH
        - go_cache/GOCACHE

  - name: publish
    image: appleboy/drone-scp
    pull: always
    settings:
      host:
        from_secret: server_host
      username: root
      password:
        from_secret: ssh_password
      port: 22
      command_timeout: 3m
      overwrite: true
      target: /data/userSite
      source:
        - hx
        - docs
        - Makefile

  - name: deploy
    image: appleboy/drone-ssh
    pull: always
    settings:
      host:
        from_secret: server_host
      username: root
      password:
        from_secret: ssh_password
      port: 22
      command_timeout: 3m
      script:
        - cd /data/userSite
        - make deploy

  - name: status
    image: appleboy/drone-ssh
    pull: if-not-exists
    settings:
      host:
        from_secret: server_host
      username: root
      password:
        from_secret: ssh_password
      port: 22
      command_timeout: 3m
      script:
        - cd /data/userSite
        - make status
    when:
      status:
        - success
        - failure

volumes:
  - name: cache
    host:
      path: /tmp/cache

trigger:
  branch:
    - master
