kind: pipeline
type: docker
name: linux_amd64

environment:
  GOOS: linux
  GOARCH: amd64
  CGO_ENABLED: 0
  GO111MODULE: on

steps:
  # - name: build
  #   image: golang:1.17
  #   pull: if-not-exists
  #   commands:
  #     - pwd
  #     - go version
  #     - go build -v -a -o app

  - name: scp
    image: appleboy/drone-scp
    pull: always
    settings:
      host:
       from_secret: server_host
      username: root
      password:
        from_secret: ssh_password
      port: 22
      command_timeout: 2m
      overwrite: true
      target: ./*
      source: /data/app/ 
     
     
