kind: pipeline
type: docker
name: hx_linux_amd64

workspace:
  path: /github.com/dry-indus/hx  

environment:
  GOOS: linux
  GOARCH: amd64
  CGO_ENABLED: 0
  GO111MODULE: on

steps:
  - name: build
    image: golang:1.17
    pull: if-not-exists
    commands:
      - make build

  - name: publish
    image: appleboy/drone-scp
    pull: always
    settings:
      host:
       from_secret: server_host
      username: root
      password:
        from_secret: ssh_password
      port: 22
      command_timeout: 1m
      overwrite: true
      target: /data/userSite
      source: 
        - hx
        - docs
        - Makefile

  - name: deploy
    image: appleboy/drone-ssh
    pull: always
    settings:
      host:
        from_secret: server_host
      username: root
      password:
        from_secret: ssh_password
      port: 22
      script:
        - cd /data/userSite
        - make deploy 

trigger:
  branch:
  - master