kind: pipeline
type: docker
name: linux_amd64

environment:
  GOOS: linux
  GOARCH: amd64
  CGO_ENABLED: 0
  GO111MODULE: on

steps:
  - name: build
    image: golang:1.17
    pull: if-not-exists
    when:
      branch: [master]
    commands:
      - pwd
      - go version
      - go build -v -a -o app
      - go install github.com/swaggo/swag/cmd/swag@latest
      - rm -rf docs
      - swag i -g api/merchant/v1/api.go --exclude ./controller/userctr --instanceName mv1
      - swag i -g api/user/v1/api.go --exclude ./controller/merchantctr --instanceName uv1

  - name: publish
    image: appleboy/drone-scp
    pull: always
    settings:
      host:
       from_secret: server_host
      username: root
      password:
        from_secret: ssh_password
      port: 22
      command_timeout: 1m
      overwrite: true
      target: /data/userSite
      source: 
        - app
        - docs

  - name: deploy
    image: appleboy/drone-ssh
    pull: always
    settings:
      host:
        from_secret: server_host
      username: root
      password:
        from_secret: ssh_password
      port: 22
      command_timeout: 1m
      script:
        - systemctl stop usersite
        - cd /data/userSite && mv app usersite
        - systemctl restart usersite
        # - systemctl is-active siteuser | grep inactive | grep -q . && exit 1 