kind: pipeline
type: docker
name: linux_amd64

environment:
  GOOS: linux
  GOARCH: amd64
  CGO_ENABLED: 0

steps:
  - name: build
    image: golang:1.17
    pull: if-not-exists
    commands:
      - echo $SERVER_NAME
      - echo $${SERVER_NAME}
      - echo ${SERVER_NAME}
      - pwd
      - go version
      - go mod tidy
      - echo out path ${SERVER_NAME}
      - go build

  - name: publish
    image: plugins/docker:latest
    pull: if-not-exists
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      registry:
        from_secret: docker_registry
      repo: shiyanv/hx
      tags: latest

  - name: deploy
    image: appleboy/drone-ssh
    pull: always
    settings:
      host: 
        from_secret: server_host
      user: root
      key:
        from_secret: server_ssh_key
      script:
        - docker ps -q --filter name=$SERVER_NAME | grep -q . && docker stop $SERVER_NAME && docker rmi -f docker rmi -f $SERVER_NAME
        - echo "docker image pulling..."
        - docker pull $SERVER_IMAGE:latest
        - echo "docker container running..."
        - docker run -n $SERVER_NAME -p $SERVER_PORT -d example/demo
        - docker logs --tail $SERVER_NAME
