kind: pipeline
type: docker
name: linux_amd64

environment:
  GOOS: linux
  GOARCH: amd64
  CGO_ENABLED: 0
  GO111MODULE: on

steps:
  - name: build
    image: golang:1.17
    pull: if-not-exists
    commands:
      - pwd
      - go version
      - go build -v -a -o release/app
      - go install github.com/swaggo/swag/cmd/swag@latest
      - swag i -g api/merchant/v1/api.go --exclude ./controller/userctr -o release/docs/  --instanceName mv1
      - swag i -g api/user/v1/api.go --exclude ./controller/merchantctr -o release/docs/ --instanceName uv1
      - ls release

  - name: scp
    image: appleboy/drone-scp
    pull: always
    environment:
      SERVER_NAME:
        from_secret: server_name
    settings:
      host:
       from_secret: server_host
      username: root
      password:
        from_secret: ssh_password
      port: 22
      command_timeout: 2m
      overwrite: true
      target: /data/$SERVER_NAME/
      source: release/*
     
     
