kind: pipeline
type: docker
name: hx_linux_amd64

environment:
  GOOS: linux
  GOARCH: amd64
  CGO_ENABLED: 0
  GO111MODULE: on

volumes:
  - name: cache
    host:
      path: /tmp/cache

steps:
  - name: restore-cache
    image: drillster/drone-volume-cache
    pull: if-not-exists
    volumes:
      - name: cache
        path: /go
    settings:
      restore: true
      mount:
        - $GOMODCACHE
        - $GOCACHE

  - name: build
    image: golang:1.17
    pull: if-not-exists
    commands:
      - make build

  - name: rebuild-cache
    image: drillster/drone-volume-cache
    pull: if-not-exists
    volumes:
      - name: cache
        path: /go
    settings:
      rebuild: true
      mount:
        - $GOMODCACHE
        - $GOCACHE

  - name: publish
    image: appleboy/drone-scp
    pull: always
    settings:
      host:
        from_secret: server_host
      username: root
      password:
        from_secret: ssh_password
      port: 22
      command_timeout: 1m
      overwrite: true
      target: /data/userSite
      source:
        - hx
        - docs
        - Makefile

  - name: deploy
    image: appleboy/drone-ssh
    pull: always
    settings:
      host:
        from_secret: server_host
      username: root
      password:
        from_secret: ssh_password
      port: 22
      script:
        - cd /data/userSite
        - make deploy

  - name: status
    image: appleboy/drone-ssh
    pull: if-not-exists
    settings:
      host:
        from_secret: server_host
      username: root
      password:
        from_secret: ssh_password
      port: 22
      script:
        - cd /data/userSite
        - make status
    when:
      status:
        - success
        - failure

trigger:
  branch:
    - master
