kind: pipeline
type: docker
name: linux_amd64

environment:
  GOOS: linux
  GOARCH: amd64
  CGO_ENABLED: 0
  GO111MODULE: on

steps:
  - name: build
    image: golang:1.17
    pull: if-not-exists
    environment:
      SERVER_NAME:
        from_secret: server_name
      SERVER_HOST:
        from_secret: server_host
      SERVER_PORT:
        from_secret: server_port
      SERVER_IMAGE:
        from_secret: server_image
      SERVER_SSH_KEY:
        from_secret: server_ssh_key
      DOCKER_USERNAME:
        from_secret: docker_username
      DOCKER_PASSWORD:
        from_secret: docker_password
    commands:
      - pwd
      - go version
      - go build -v -a -o app

  - name: scp
    image: appleboy/drone-scp
    pull: always
    settings:
      host:
       from_secret: server_host
      username: root
      password:
        from_secret: ssh_password
      port: 22
      command_timeout: 2m
      target: app
      source: /data/app/
     
