kind: pipeline
type: docker
name: linux_amd64

environment:
  GOOS: linux
  GOARCH: amd64
  CGO_ENABLED: 0
  GO111MODULE: on

steps:
  - name: build
    image: golang:1.17
    pull: if-not-exists
    environment:
      SERVER_NAME:
        from_secret: server_name
      SERVER_HOST:
        from_secret: server_host
      SERVER_PORT:
        from_secret: server_port
      SERVER_IMAGE:
        from_secret: server_image
      SERVER_SSH_KEY:
        from_secret: server_ssh_key
      DOCKER_USERNAME:
        from_secret: docker_username
      DOCKER_PASSWORD:
        from_secret: docker_password
    commands:
      - echo $SERVER_NAME
      - echo $${SERVER_NAME}
      - echo ${SERVER_NAME}
      - echo $SERVER_HOST
      - pwd
      - go version
      - go mod tidy
      - echo out path $SERVER_NAME
      - go build

  - name: publish
    image: plugins/docker:latest
    pull: always
    environment:
      DRONE_RUNNER_VOLUMES: /var/run/docker.sock
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      registry:
        from_secret: docker_registry
      repo: shiyanv/hx
      tags: latest
    commands:
     - ls -all 
     - cat Dockerfile

  - name: deploy
    image: appleboy/drone-ssh
    pull: always
    environment:
      SERVER_NAME:
        from_secret: server_name
      SERVER_PORT:
        from_secret: server_port
      SERVER_IMAGE:
        from_secret: server_image
    settings:
      host: 
        from_secret: server_host
      user: root
      key:
        from_secret: server_ssh_key
      script:
        - docker ps -q --filter name=$SERVER_NAME | grep -q . && docker stop $SERVER_NAME && docker rmi -f docker rmi -f $SERVER_NAME
        - echo "docker image pulling..."
        - docker pull $SERVER_IMAGE:latest
        - echo "docker container running..."
        - docker run -n $SERVER_NAME -p $SERVER_PORT -d example/demo
        - docker logs --tail $SERVER_NAME
