// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {},
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/v1/user/home/list/{xx_merchant}": {
            "post": {
                "description": "首页核心接口，展示商品列表",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户-首页"
                ],
                "summary": "商品列表",
                "parameters": [
                    {
                        "description": "参数",
                        "name": "param",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/usermod.HomeListRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "商品列表",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.HTTPResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "Data": {
                                            "$ref": "#/definitions/usermod.HomeListResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "参数错误",
                        "schema": {
                            "$ref": "#/definitions/response.HTTPResponse"
                        }
                    },
                    "500": {
                        "description": "内部错误",
                        "schema": {
                            "$ref": "#/definitions/response.HTTPResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "response.HTTPResponse": {
            "type": "object",
            "properties": {
                "data": {},
                "message": {
                    "type": "string"
                },
                "status": {
                    "type": "integer"
                }
            }
        },
        "usermod.Commodity": {
            "type": "object",
            "properties": {
                "commodityID": {
                    "type": "string"
                },
                "picURL": {
                    "type": "string"
                },
                "tags": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/usermod.Tags"
                    }
                }
            }
        },
        "usermod.HomeListRequest": {
            "type": "object",
            "required": [
                "pageNumber",
                "pageSize"
            ],
            "properties": {
                "pageNumber": {
                    "description": "当前页",
                    "type": "integer",
                    "minimum": 1
                },
                "pageSize": {
                    "description": "每页条数",
                    "type": "integer",
                    "maximum": 20,
                    "minimum": 1
                }
            }
        },
        "usermod.HomeListResponse": {
            "type": "object",
            "properties": {
                "hasNext": {
                    "type": "boolean"
                },
                "list": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/usermod.Commodity"
                    }
                }
            }
        },
        "usermod.Tags": {
            "type": "object",
            "properties": {
                "tagID": {
                    "type": "string"
                },
                "tagName": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:7777",
	BasePath:         "/v1/user",
	Schemes:          []string{},
	Title:            "HaiXian API",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
