// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplatemv1 = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {},
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/auth/login": {
            "post": {
                "description": "商户登陆",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "商户-鉴权"
                ],
                "summary": "登陆",
                "parameters": [
                    {
                        "description": "参数",
                        "name": "param",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/merchantmod.LoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.HTTPResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "Data": {
                                            "$ref": "#/definitions/merchantmod.LoginResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "失败",
                        "schema": {
                            "$ref": "#/definitions/response.HTTPResponse"
                        }
                    }
                }
            }
        },
        "/auth/logout": {
            "post": {
                "security": [
                    {
                        "Auth": []
                    }
                ],
                "description": "商户注销",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "商户-鉴权"
                ],
                "summary": "注销",
                "parameters": [
                    {
                        "description": "参数",
                        "name": "param",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/merchantmod.LogoutRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.HTTPResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "Data": {
                                            "$ref": "#/definitions/merchantmod.LogoutResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "失败",
                        "schema": {
                            "$ref": "#/definitions/response.HTTPResponse"
                        }
                    }
                }
            }
        },
        "/auth/register": {
            "post": {
                "description": "商户注册",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "商户-鉴权"
                ],
                "summary": "注册",
                "parameters": [
                    {
                        "description": "参数",
                        "name": "param",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/merchantmod.RegisterRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.HTTPResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "Data": {
                                            "$ref": "#/definitions/merchantmod.RegisterResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "失败",
                        "schema": {
                            "$ref": "#/definitions/response.HTTPResponse"
                        }
                    }
                }
            }
        },
        "/commodity/add": {
            "post": {
                "security": [
                    {
                        "Auth": []
                    }
                ],
                "description": "添加商品",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "商户-商品"
                ],
                "summary": "添加商品",
                "parameters": [
                    {
                        "description": "参数",
                        "name": "param",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/merchantmod.CommodityAddRequest"
                        }
                    },
                    {
                        "type": "string",
                        "description": "hoken",
                        "name": "hoken",
                        "in": "header"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.HTTPResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "Data": {
                                            "$ref": "#/definitions/merchantmod.CommodityAddResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "失败",
                        "schema": {
                            "$ref": "#/definitions/response.HTTPResponse"
                        }
                    }
                }
            }
        },
        "/commodity/del": {
            "post": {
                "security": [
                    {
                        "Auth": []
                    }
                ],
                "description": "删除商品",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "商户-商品"
                ],
                "summary": "删除商品",
                "parameters": [
                    {
                        "description": "参数",
                        "name": "param",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/merchantmod.CommodityDelRequest"
                        }
                    },
                    {
                        "type": "string",
                        "description": "hoken",
                        "name": "hoken",
                        "in": "header"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.HTTPResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "Data": {
                                            "$ref": "#/definitions/merchantmod.CommodityDelResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "失败\"                                       \"内部服务错误",
                        "schema": {
                            "$ref": "#/definitions/response.HTTPResponse"
                        }
                    }
                }
            }
        },
        "/commodity/hide": {
            "post": {
                "security": [
                    {
                        "Auth": []
                    }
                ],
                "description": "商品隐藏后，用户不可见",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "商户-商品"
                ],
                "summary": "隐藏商品",
                "parameters": [
                    {
                        "description": "参数",
                        "name": "param",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/merchantmod.CommodityHideRequest"
                        }
                    },
                    {
                        "type": "string",
                        "description": "hoken",
                        "name": "hoken",
                        "in": "header"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.HTTPResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "Data": {
                                            "$ref": "#/definitions/merchantmod.CommodityHideResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "失败",
                        "schema": {
                            "$ref": "#/definitions/response.HTTPResponse"
                        }
                    }
                }
            }
        },
        "/commodity/list": {
            "post": {
                "security": [
                    {
                        "Auth": []
                    }
                ],
                "description": "商品列表",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "商户-商品"
                ],
                "summary": "商品列表",
                "parameters": [
                    {
                        "description": "参数",
                        "name": "param",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/merchantmod.CommodityListRequest"
                        }
                    },
                    {
                        "type": "string",
                        "description": "hoken",
                        "name": "hoken",
                        "in": "header"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.HTTPResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "Data": {
                                            "$ref": "#/definitions/merchantmod.CommodityListResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/response.HTTPResponse"
                        }
                    }
                }
            }
        },
        "/commodity/modify": {
            "post": {
                "security": [
                    {
                        "Auth": []
                    }
                ],
                "description": "编辑商品",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "商户-商品"
                ],
                "summary": "编辑商品",
                "parameters": [
                    {
                        "description": "参数",
                        "name": "param",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/merchantmod.CommodityModifyRequest"
                        }
                    },
                    {
                        "type": "string",
                        "description": "hoken",
                        "name": "hoken",
                        "in": "header"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.HTTPResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "Data": {
                                            "$ref": "#/definitions/merchantmod.CommodityModifyResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "失败",
                        "schema": {
                            "$ref": "#/definitions/response.HTTPResponse"
                        }
                    }
                }
            }
        },
        "/commodity/publish": {
            "post": {
                "security": [
                    {
                        "Auth": []
                    }
                ],
                "description": "商品发布后，用户可见",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "商户-商品"
                ],
                "summary": "发布商品",
                "parameters": [
                    {
                        "description": "参数",
                        "name": "param",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/merchantmod.CommodityPublishRequest"
                        }
                    },
                    {
                        "type": "string",
                        "description": "hoken",
                        "name": "hoken",
                        "in": "header"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.HTTPResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "Data": {
                                            "$ref": "#/definitions/merchantmod.CommodityPublishResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "失败",
                        "schema": {
                            "$ref": "#/definitions/response.HTTPResponse"
                        }
                    }
                }
            }
        },
        "/commodity/sp/add": {
            "post": {
                "security": [
                    {
                        "Auth": []
                    }
                ],
                "description": "添加商品规格与定价",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "商户-商品规格与定价"
                ],
                "summary": "添加商品规格与定价",
                "parameters": [
                    {
                        "description": "参数",
                        "name": "param",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/merchantmod.SPAddRequest"
                        }
                    },
                    {
                        "type": "string",
                        "description": "hoken",
                        "name": "hoken",
                        "in": "header"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.HTTPResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "Data": {
                                            "$ref": "#/definitions/merchantmod.SPAddResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "失败",
                        "schema": {
                            "$ref": "#/definitions/response.HTTPResponse"
                        }
                    }
                }
            }
        },
        "/commodity/sp/del": {
            "post": {
                "security": [
                    {
                        "Auth": []
                    }
                ],
                "description": "删除商品规格与定价，每个商品至少保留一项",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "商户-商品规格与定价"
                ],
                "summary": "删除商品规格与定价",
                "parameters": [
                    {
                        "description": "参数",
                        "name": "param",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/merchantmod.SPDelRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.HTTPResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "Data": {
                                            "$ref": "#/definitions/merchantmod.SPDelResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "失败",
                        "schema": {
                            "$ref": "#/definitions/response.HTTPResponse"
                        }
                    }
                }
            }
        },
        "/commodity/sp/modify": {
            "post": {
                "security": [
                    {
                        "Auth": []
                    }
                ],
                "description": "编辑商品规格与定价",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "商户-商品规格与定价"
                ],
                "summary": "编辑商品规格与定价",
                "parameters": [
                    {
                        "description": "参数",
                        "name": "param",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/merchantmod.SPModifyRequest"
                        }
                    },
                    {
                        "type": "string",
                        "description": "hoken",
                        "name": "hoken",
                        "in": "header"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.HTTPResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "Data": {
                                            "$ref": "#/definitions/merchantmod.SPModifyResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "失败",
                        "schema": {
                            "$ref": "#/definitions/response.HTTPResponse"
                        }
                    }
                }
            }
        },
        "/commodity/tag/add": {
            "post": {
                "security": [
                    {
                        "Auth": []
                    }
                ],
                "description": "添加标签",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "商户-标签"
                ],
                "summary": "添加标签",
                "parameters": [
                    {
                        "description": "参数",
                        "name": "param",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/merchantmod.TagAddRequest"
                        }
                    },
                    {
                        "type": "string",
                        "description": "hoken",
                        "name": "hoken",
                        "in": "header"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.HTTPResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "Data": {
                                            "$ref": "#/definitions/merchantmod.TagAddResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "失败",
                        "schema": {
                            "$ref": "#/definitions/response.HTTPResponse"
                        }
                    }
                }
            }
        },
        "/commodity/tag/del": {
            "post": {
                "security": [
                    {
                        "Auth": []
                    }
                ],
                "description": "删除标签",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "商户-标签"
                ],
                "summary": "删除标签",
                "parameters": [
                    {
                        "description": "参数",
                        "name": "param",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/merchantmod.TagDelRequest"
                        }
                    },
                    {
                        "type": "string",
                        "description": "hoken",
                        "name": "hoken",
                        "in": "header"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.HTTPResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "Data": {
                                            "$ref": "#/definitions/merchantmod.TagDelResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "失败",
                        "schema": {
                            "$ref": "#/definitions/response.HTTPResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "merchantmod.Commodity": {
            "type": "object",
            "properties": {
                "category": {
                    "description": "Category 1:餐饮,2:服饰",
                    "type": "integer",
                    "enum": [
                        1,
                        2
                    ]
                },
                "count": {
                    "description": "Count 商品数量",
                    "type": "integer"
                },
                "createdAt": {
                    "description": "CreatedAt 商品创建时间",
                    "type": "string"
                },
                "id": {
                    "description": "ID 商品id",
                    "type": "string"
                },
                "name": {
                    "description": "Name 商品名称",
                    "type": "string"
                },
                "online": {
                    "description": "Online 1:Online,2:Offline",
                    "type": "integer",
                    "enum": [
                        0,
                        1
                    ]
                },
                "picUrl": {
                    "description": "Name 商品缩略图",
                    "type": "string"
                },
                "show": {
                    "description": "Show 3:Show,4:Hide",
                    "type": "integer",
                    "enum": [
                        2,
                        3
                    ]
                },
                "sps": {
                    "description": "SPs 商品规格与定价,至少有一项",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/merchantmod.SP"
                    }
                },
                "tags": {
                    "description": "Tags 商品标签",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/merchantmod.Tag"
                    }
                },
                "weight": {
                    "description": "Weight 权重，控制显示顺序 desc",
                    "type": "integer"
                }
            }
        },
        "merchantmod.CommodityAdd": {
            "type": "object",
            "required": [
                "picURL",
                "sps"
            ],
            "properties": {
                "name": {
                    "description": "Name 商品名称",
                    "type": "string"
                },
                "picURL": {
                    "description": "PicURL 商品缩略图",
                    "type": "string"
                },
                "sps": {
                    "description": "SPs 商品规格和定价,至少有一项",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/merchantmod.SP"
                    }
                },
                "tags": {
                    "description": "Tags 商品标签",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/merchantmod.Tag"
                    }
                }
            }
        },
        "merchantmod.CommodityAddRequest": {
            "type": "object",
            "required": [
                "commoditys"
            ],
            "properties": {
                "commoditys": {
                    "description": "Commoditys 需要添加的商品列表",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/merchantmod.CommodityAdd"
                    }
                }
            }
        },
        "merchantmod.CommodityAddResponse": {
            "type": "object",
            "properties": {
                "count": {
                    "description": "Count 新增商品数量",
                    "type": "integer"
                },
                "ids": {
                    "description": "Ids 新增商品id",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "merchantmod.CommodityDelRequest": {
            "type": "object",
            "required": [
                "id"
            ],
            "properties": {
                "id": {
                    "description": "Id 商品id",
                    "type": "string"
                }
            }
        },
        "merchantmod.CommodityDelResponse": {
            "type": "object"
        },
        "merchantmod.CommodityHideRequest": {
            "type": "object",
            "required": [
                "id"
            ],
            "properties": {
                "id": {
                    "description": "Id 商品id",
                    "type": "string"
                }
            }
        },
        "merchantmod.CommodityHideResponse": {
            "type": "object"
        },
        "merchantmod.CommodityListRequest": {
            "type": "object",
            "required": [
                "pageNumber",
                "pageSize"
            ],
            "properties": {
                "pageNumber": {
                    "description": "Limit (min 1)",
                    "type": "integer",
                    "minimum": 1
                },
                "pageSize": {
                    "description": "Limit (min 1,max 20)",
                    "type": "integer",
                    "maximum": 20,
                    "minimum": 1
                }
            }
        },
        "merchantmod.CommodityListResponse": {
            "type": "object",
            "properties": {
                "allTags": {
                    "description": "AllTags 商户设置的所有标签",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/merchantmod.Tag"
                    }
                },
                "hasNext": {
                    "description": "HasNext true: 有下一页，否则没有下一页",
                    "type": "boolean"
                },
                "list": {
                    "description": "List 商品列表",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/merchantmod.Commodity"
                    }
                }
            }
        },
        "merchantmod.CommodityModifyRequest": {
            "type": "object",
            "required": [
                "id"
            ],
            "properties": {
                "id": {
                    "description": "Id 商品id",
                    "type": "string"
                },
                "name": {
                    "description": "PicURL 商品名称",
                    "type": "string"
                },
                "picURL": {
                    "description": "PicURL 商品缩略图",
                    "type": "string"
                },
                "tags": {
                    "description": "Tags 重设的标签列表, 仅设置selected:true 的标签\nexample: [{\"id\":\"id\",\"selected\":true}]",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/merchantmod.Tag"
                    }
                }
            }
        },
        "merchantmod.CommodityModifyResponse": {
            "type": "object",
            "properties": {
                "id": {
                    "description": "Id 商品id",
                    "type": "string"
                }
            }
        },
        "merchantmod.CommodityPublishRequest": {
            "type": "object",
            "required": [
                "id"
            ],
            "properties": {
                "id": {
                    "description": "Id 商品id",
                    "type": "string"
                }
            }
        },
        "merchantmod.CommodityPublishResponse": {
            "type": "object"
        },
        "merchantmod.LoginRequest": {
            "type": "object",
            "required": [
                "name",
                "password"
            ],
            "properties": {
                "code": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "merchantmod.LoginResponse": {
            "type": "object",
            "properties": {
                "category": {
                    "description": "Category 1:餐饮,2:服饰",
                    "type": "integer",
                    "enum": [
                        1,
                        2
                    ]
                },
                "name": {
                    "type": "string"
                },
                "telegram": {
                    "type": "string"
                }
            }
        },
        "merchantmod.LogoutRequest": {
            "type": "object"
        },
        "merchantmod.LogoutResponse": {
            "type": "object"
        },
        "merchantmod.RegisterRequest": {
            "type": "object",
            "required": [
                "category",
                "name",
                "password",
                "passwordTwo",
                "telegram"
            ],
            "properties": {
                "category": {
                    "description": "Category 1:餐饮,2:服饰",
                    "type": "integer",
                    "enum": [
                        1,
                        2
                    ]
                },
                "code": {
                    "type": "string"
                },
                "name": {
                    "description": "Name is user account",
                    "type": "string"
                },
                "password": {
                    "description": "Password is user login password",
                    "type": "string"
                },
                "passwordTwo": {
                    "description": "PasswordTwo 二次输入密码，必须和Password 一致",
                    "type": "string"
                },
                "telegram": {
                    "description": "Telegram 小飞机账号",
                    "type": "string"
                }
            }
        },
        "merchantmod.RegisterResponse": {
            "type": "object",
            "properties": {
                "category": {
                    "description": "Category 1:餐饮,2:服饰",
                    "type": "integer",
                    "enum": [
                        1,
                        2
                    ]
                },
                "name": {
                    "type": "string"
                },
                "telegram": {
                    "type": "string"
                }
            }
        },
        "merchantmod.SP": {
            "type": "object",
            "required": [
                "pricing",
                "specifications"
            ],
            "properties": {
                "choiceOpt": {
                    "description": "ChoiceOpt 选择设置 0:单选；1:多选；2:必选",
                    "type": "integer",
                    "enum": [
                        0,
                        1,
                        2
                    ]
                },
                "id": {
                    "description": "Id 规格和定价id",
                    "type": "string"
                },
                "picUrl": {
                    "description": "PicURL 规格和价格缩略图",
                    "type": "string"
                },
                "pricing": {
                    "description": "Pricing 商品定价\nexample: 10，10.5",
                    "type": "number"
                },
                "specifications": {
                    "description": "Specifications 商品规格\nexample: 一个，一份，一碗，一件",
                    "type": "string"
                }
            }
        },
        "merchantmod.SPAddRequest": {
            "type": "object",
            "required": [
                "commodityId",
                "pricing",
                "specifications"
            ],
            "properties": {
                "choiceOpt": {
                    "description": "ChoiceOpt 选择设置 0:单选；1:多选；2:必选",
                    "type": "integer",
                    "enum": [
                        0,
                        1,
                        2
                    ]
                },
                "commodityId": {
                    "description": "CommodityId 商品id",
                    "type": "string"
                },
                "picUrl": {
                    "description": "PicURL 规格与定价缩略图",
                    "type": "string"
                },
                "pricing": {
                    "description": "Pricing 商品定价",
                    "type": "number"
                },
                "specifications": {
                    "description": "Specifications 商品规格",
                    "type": "string"
                }
            }
        },
        "merchantmod.SPAddResponse": {
            "type": "object",
            "properties": {
                "id": {
                    "description": "Id 规格与定价id",
                    "type": "string"
                }
            }
        },
        "merchantmod.SPDelRequest": {
            "type": "object",
            "required": [
                "id"
            ],
            "properties": {
                "id": {
                    "description": "Id 规格与定价id",
                    "type": "string"
                }
            }
        },
        "merchantmod.SPDelResponse": {
            "type": "object"
        },
        "merchantmod.SPModifyRequest": {
            "type": "object",
            "required": [
                "id",
                "pricing",
                "specifications"
            ],
            "properties": {
                "choiceOpt": {
                    "description": "ChoiceOpt 选择设置 0:单选；1:多选；2:必选",
                    "type": "integer",
                    "enum": [
                        0,
                        1,
                        2
                    ]
                },
                "id": {
                    "description": "Id 规格与定价id",
                    "type": "string"
                },
                "picUrl": {
                    "description": "PicURL 规格与定价缩略图",
                    "type": "string"
                },
                "pricing": {
                    "description": "Pricing 商品定价",
                    "type": "number"
                },
                "specifications": {
                    "description": "Specifications 商品规格",
                    "type": "string"
                }
            }
        },
        "merchantmod.SPModifyResponse": {
            "type": "object",
            "properties": {
                "id": {
                    "description": "Id 规格与定价id",
                    "type": "string"
                }
            }
        },
        "merchantmod.Tag": {
            "type": "object",
            "properties": {
                "id": {
                    "description": "ID 标签id",
                    "type": "string"
                },
                "name": {
                    "description": "Name 标签名",
                    "type": "string"
                },
                "selected": {
                    "description": "Selected true:已选择，否则未选择",
                    "type": "boolean"
                }
            }
        },
        "merchantmod.TagAddRequest": {
            "type": "object",
            "required": [
                "commodityId",
                "name"
            ],
            "properties": {
                "commodityId": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "merchantmod.TagAddResponse": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                }
            }
        },
        "merchantmod.TagDelRequest": {
            "type": "object",
            "required": [
                "id"
            ],
            "properties": {
                "id": {
                    "type": "string"
                }
            }
        },
        "merchantmod.TagDelResponse": {
            "type": "object"
        },
        "response.HTTPResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "description": "数据"
                },
                "message": {
                    "description": "信息",
                    "type": "string"
                },
                "status": {
                    "description": "Status 1000: Invalid Param,\nStatus 2000: Internal Server Error\nStatus 3000: Tip\nStatus 4000: Reload\nStatus 5000: Relogin\nStatus 6000: Redirect",
                    "type": "integer",
                    "enum": [
                        1000,
                        2000,
                        3000,
                        4000,
                        5000,
                        6000
                    ]
                }
            }
        }
    },
    "securityDefinitions": {
        "Auth": {
            "type": "apiKey",
            "name": "hoken",
            "in": "header"
        }
    }
}`

// SwaggerInfomv1 holds exported Swagger Info so clients can modify it
var SwaggerInfomv1 = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:7777",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "HaiXian 商户 API",
	Description:      "",
	InfoInstanceName: "mv1",
	SwaggerTemplate:  docTemplatemv1,
}

func init() {
	swag.Register(SwaggerInfomv1.InstanceName(), SwaggerInfomv1)
}
