// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplatemv1 = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {},
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/auth/login": {
            "post": {
                "description": "商户登陆",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "商户-鉴权"
                ],
                "summary": "登陆",
                "parameters": [
                    {
                        "description": "参数",
                        "name": "param",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/merchantmod.LoginRequest"
                        }
                    },
                    {
                        "type": "string",
                        "default": "zh-CN",
                        "description": "语言",
                        "name": "language",
                        "in": "header"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.HTTPResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "Data": {
                                            "$ref": "#/definitions/merchantmod.LoginResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "失败",
                        "schema": {
                            "$ref": "#/definitions/response.HTTPResponse"
                        }
                    }
                }
            }
        },
        "/auth/logout": {
            "post": {
                "security": [
                    {
                        "Auth": []
                    }
                ],
                "description": "商户注销",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "商户-鉴权"
                ],
                "summary": "注销",
                "parameters": [
                    {
                        "description": "参数",
                        "name": "param",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/merchantmod.LogoutRequest"
                        }
                    },
                    {
                        "type": "string",
                        "default": "zh-CN",
                        "description": "语言",
                        "name": "language",
                        "in": "header"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.HTTPResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "Data": {
                                            "$ref": "#/definitions/merchantmod.LogoutResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "失败",
                        "schema": {
                            "$ref": "#/definitions/response.HTTPResponse"
                        }
                    }
                }
            }
        },
        "/auth/register": {
            "post": {
                "description": "商户注册",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "商户-鉴权"
                ],
                "summary": "注册",
                "parameters": [
                    {
                        "description": "参数",
                        "name": "param",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/merchantmod.RegisterRequest"
                        }
                    },
                    {
                        "type": "string",
                        "default": "zh-CN",
                        "description": "语言",
                        "name": "language",
                        "in": "header"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.HTTPResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "Data": {
                                            "$ref": "#/definitions/merchantmod.RegisterResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "失败",
                        "schema": {
                            "$ref": "#/definitions/response.HTTPResponse"
                        }
                    }
                }
            }
        },
        "/commodity/add": {
            "post": {
                "security": [
                    {
                        "Auth": []
                    }
                ],
                "description": "添加商品",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "商户-商品"
                ],
                "summary": "添加商品",
                "parameters": [
                    {
                        "description": "参数",
                        "name": "param",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/merchantmod.CommodityAddRequest"
                        }
                    },
                    {
                        "type": "string",
                        "description": "hoken",
                        "name": "hoken",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "default": "zh-CN",
                        "description": "语言",
                        "name": "language",
                        "in": "header"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.HTTPResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "Data": {
                                            "$ref": "#/definitions/merchantmod.CommodityAddResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "失败",
                        "schema": {
                            "$ref": "#/definitions/response.HTTPResponse"
                        }
                    }
                }
            }
        },
        "/commodity/del": {
            "post": {
                "security": [
                    {
                        "Auth": []
                    }
                ],
                "description": "删除商品",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "商户-商品"
                ],
                "summary": "删除商品",
                "parameters": [
                    {
                        "description": "参数",
                        "name": "param",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/merchantmod.CommodityDelRequest"
                        }
                    },
                    {
                        "type": "string",
                        "description": "hoken",
                        "name": "hoken",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "default": "zh-CN",
                        "description": "语言",
                        "name": "language",
                        "in": "header"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.HTTPResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "Data": {
                                            "$ref": "#/definitions/merchantmod.CommodityDelResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "失败\"                                       \"内部服务错误",
                        "schema": {
                            "$ref": "#/definitions/response.HTTPResponse"
                        }
                    }
                }
            }
        },
        "/commodity/hide": {
            "post": {
                "security": [
                    {
                        "Auth": []
                    }
                ],
                "description": "商品隐藏后，用户不可见",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "商户-商品"
                ],
                "summary": "隐藏商品",
                "parameters": [
                    {
                        "description": "参数",
                        "name": "param",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/merchantmod.CommodityHideRequest"
                        }
                    },
                    {
                        "type": "string",
                        "description": "hoken",
                        "name": "hoken",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "default": "zh-CN",
                        "description": "语言",
                        "name": "language",
                        "in": "header"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.HTTPResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "Data": {
                                            "$ref": "#/definitions/merchantmod.CommodityHideResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "失败",
                        "schema": {
                            "$ref": "#/definitions/response.HTTPResponse"
                        }
                    }
                }
            }
        },
        "/commodity/list": {
            "post": {
                "security": [
                    {
                        "Auth": []
                    }
                ],
                "description": "商品列表",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "商户-商品"
                ],
                "summary": "商品列表",
                "parameters": [
                    {
                        "description": "参数",
                        "name": "param",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/merchantmod.CommodityListRequest"
                        }
                    },
                    {
                        "type": "string",
                        "description": "hoken",
                        "name": "hoken",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "default": "zh-CN",
                        "description": "语言",
                        "name": "language",
                        "in": "header"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.HTTPResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "Data": {
                                            "$ref": "#/definitions/merchantmod.CommodityListResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/response.HTTPResponse"
                        }
                    }
                }
            }
        },
        "/commodity/modify": {
            "post": {
                "security": [
                    {
                        "Auth": []
                    }
                ],
                "description": "编辑商品",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "商户-商品"
                ],
                "summary": "编辑商品",
                "parameters": [
                    {
                        "description": "参数",
                        "name": "param",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/merchantmod.CommodityModifyRequest"
                        }
                    },
                    {
                        "type": "string",
                        "description": "hoken",
                        "name": "hoken",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "default": "zh-CN",
                        "description": "语言",
                        "name": "language",
                        "in": "header"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.HTTPResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "Data": {
                                            "$ref": "#/definitions/merchantmod.CommodityModifyResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "失败",
                        "schema": {
                            "$ref": "#/definitions/response.HTTPResponse"
                        }
                    }
                }
            }
        },
        "/commodity/publish": {
            "post": {
                "security": [
                    {
                        "Auth": []
                    }
                ],
                "description": "商品发布后，用户可见",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "商户-商品"
                ],
                "summary": "发布商品",
                "parameters": [
                    {
                        "description": "参数",
                        "name": "param",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/merchantmod.CommodityPublishRequest"
                        }
                    },
                    {
                        "type": "string",
                        "description": "hoken",
                        "name": "hoken",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "default": "zh-CN",
                        "description": "语言",
                        "name": "language",
                        "in": "header"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.HTTPResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "Data": {
                                            "$ref": "#/definitions/merchantmod.CommodityPublishResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "失败",
                        "schema": {
                            "$ref": "#/definitions/response.HTTPResponse"
                        }
                    }
                }
            }
        },
        "/commodity/sp/add": {
            "post": {
                "security": [
                    {
                        "Auth": []
                    }
                ],
                "description": "添加商品规格与定价",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "商户-商品规格与定价"
                ],
                "summary": "添加商品规格与定价",
                "parameters": [
                    {
                        "description": "参数",
                        "name": "param",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/merchantmod.SPAddRequest"
                        }
                    },
                    {
                        "type": "string",
                        "description": "hoken",
                        "name": "hoken",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "default": "zh-CN",
                        "description": "语言",
                        "name": "language",
                        "in": "header"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.HTTPResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "Data": {
                                            "$ref": "#/definitions/merchantmod.SPAddResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "失败",
                        "schema": {
                            "$ref": "#/definitions/response.HTTPResponse"
                        }
                    }
                }
            }
        },
        "/commodity/sp/del": {
            "post": {
                "security": [
                    {
                        "Auth": []
                    }
                ],
                "description": "删除商品规格与定价，每个商品至少保留一项",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "商户-商品规格与定价"
                ],
                "summary": "删除商品规格与定价",
                "parameters": [
                    {
                        "description": "参数",
                        "name": "param",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/merchantmod.SPDelRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.HTTPResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "Data": {
                                            "$ref": "#/definitions/merchantmod.SPDelResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "失败",
                        "schema": {
                            "$ref": "#/definitions/response.HTTPResponse"
                        }
                    }
                }
            }
        },
        "/commodity/sp/modify": {
            "post": {
                "security": [
                    {
                        "Auth": []
                    }
                ],
                "description": "编辑商品规格与定价",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "商户-商品规格与定价"
                ],
                "summary": "编辑商品规格与定价",
                "parameters": [
                    {
                        "description": "参数",
                        "name": "param",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/merchantmod.SPModifyRequest"
                        }
                    },
                    {
                        "type": "string",
                        "description": "hoken",
                        "name": "hoken",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "default": "zh-CN",
                        "description": "语言",
                        "name": "language",
                        "in": "header"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.HTTPResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "Data": {
                                            "$ref": "#/definitions/merchantmod.SPModifyResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "失败",
                        "schema": {
                            "$ref": "#/definitions/response.HTTPResponse"
                        }
                    }
                }
            }
        },
        "/commodity/tag/add": {
            "post": {
                "security": [
                    {
                        "Auth": []
                    }
                ],
                "description": "添加标签",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "商户-标签"
                ],
                "summary": "添加标签",
                "parameters": [
                    {
                        "description": "参数",
                        "name": "param",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/merchantmod.TagAddRequest"
                        }
                    },
                    {
                        "type": "string",
                        "description": "hoken",
                        "name": "hoken",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "default": "zh-CN",
                        "description": "语言",
                        "name": "language",
                        "in": "header"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.HTTPResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "Data": {
                                            "$ref": "#/definitions/merchantmod.TagAddResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "失败",
                        "schema": {
                            "$ref": "#/definitions/response.HTTPResponse"
                        }
                    }
                }
            }
        },
        "/commodity/tag/del": {
            "post": {
                "security": [
                    {
                        "Auth": []
                    }
                ],
                "description": "删除标签",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "商户-标签"
                ],
                "summary": "删除标签",
                "parameters": [
                    {
                        "description": "参数",
                        "name": "param",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/merchantmod.TagDelRequest"
                        }
                    },
                    {
                        "type": "string",
                        "description": "hoken",
                        "name": "hoken",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "default": "zh-CN",
                        "description": "语言",
                        "name": "language",
                        "in": "header"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.HTTPResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "Data": {
                                            "$ref": "#/definitions/merchantmod.TagDelResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "失败",
                        "schema": {
                            "$ref": "#/definitions/response.HTTPResponse"
                        }
                    }
                }
            }
        },
        "/file/status": {
            "post": {
                "security": [
                    {
                        "Auth": []
                    }
                ],
                "description": "状态包括当前文件的总大小和已经上传的大小，以及上传的错误信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "文件-上传"
                ],
                "summary": "获取指定任务id的文件上传状态",
                "parameters": [
                    {
                        "description": "参数",
                        "name": "param",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/merchantmod.FileStatusRequest"
                        }
                    },
                    {
                        "type": "string",
                        "description": "hoken",
                        "name": "hoken",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "default": "zh-CN",
                        "description": "语言",
                        "name": "language",
                        "in": "header"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.HTTPResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "Data": {
                                            "$ref": "#/definitions/merchantmod.FileStatusResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/response.HTTPResponse"
                        }
                    }
                }
            }
        },
        "/file/upload": {
            "post": {
                "security": [
                    {
                        "Auth": []
                    }
                ],
                "description": "异步文件上传，该请求会立即返回当前上传状态。",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "文件-上传"
                ],
                "summary": "上传文件",
                "parameters": [
                    {
                        "type": "file",
                        "description": "文件",
                        "name": "file",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "hoken",
                        "name": "hoken",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "default": "zh-CN",
                        "description": "语言",
                        "name": "language",
                        "in": "header"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.HTTPResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "Data": {
                                            "$ref": "#/definitions/merchantmod.FileUploadResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/response.HTTPResponse"
                        }
                    }
                }
            }
        },
        "/verify/{sence}/code/send": {
            "post": {
                "description": "发送验证码",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "商户-验证"
                ],
                "summary": "发送验证码",
                "parameters": [
                    {
                        "description": "参数",
                        "name": "param",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/merchantmod.SendCodeRequest"
                        }
                    },
                    {
                        "type": "string",
                        "default": "register",
                        "description": "验证场景",
                        "name": "sence",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "default": "zh-CN",
                        "description": "语言",
                        "name": "language",
                        "in": "header"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.HTTPResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "Data": {
                                            "$ref": "#/definitions/merchantmod.SendCodeResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "失败",
                        "schema": {
                            "$ref": "#/definitions/response.HTTPResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "merchantmod.Commodity": {
            "type": "object",
            "properties": {
                "category": {
                    "description": "Category 1:餐饮,2:服饰",
                    "type": "integer",
                    "enum": [
                        1,
                        2
                    ]
                },
                "count": {
                    "description": "Count 商品数量",
                    "type": "integer"
                },
                "createdAt": {
                    "description": "CreatedAt 商品创建时间",
                    "type": "string"
                },
                "id": {
                    "description": "ID 商品id",
                    "type": "string"
                },
                "name": {
                    "description": "Name 商品名称",
                    "type": "string"
                },
                "online": {
                    "description": "Online 1:Online,2:Offline",
                    "type": "integer",
                    "enum": [
                        0,
                        1
                    ]
                },
                "picUrl": {
                    "description": "Name 商品缩略图",
                    "type": "string"
                },
                "show": {
                    "description": "Show 3:Show,4:Hide",
                    "type": "integer",
                    "enum": [
                        2,
                        3
                    ]
                },
                "sps": {
                    "description": "SPs 商品规格与定价,至少有一项",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/merchantmod.SP"
                    }
                },
                "tags": {
                    "description": "Tags 商品标签",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/merchantmod.Tag"
                    }
                },
                "weight": {
                    "description": "Weight 权重，控制显示顺序 desc",
                    "type": "integer"
                }
            }
        },
        "merchantmod.CommodityAdd": {
            "type": "object",
            "required": [
                "picURL",
                "sps"
            ],
            "properties": {
                "name": {
                    "description": "Name 商品名称",
                    "type": "string"
                },
                "picURL": {
                    "description": "PicURL 商品缩略图",
                    "type": "string"
                },
                "sps": {
                    "description": "SPs 商品规格和定价,至少有一项",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/merchantmod.SP"
                    }
                },
                "tags": {
                    "description": "Tags 商品标签",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/merchantmod.Tag"
                    }
                }
            }
        },
        "merchantmod.CommodityAddRequest": {
            "type": "object",
            "required": [
                "commoditys"
            ],
            "properties": {
                "commoditys": {
                    "description": "Commoditys 需要添加的商品列表",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/merchantmod.CommodityAdd"
                    }
                }
            }
        },
        "merchantmod.CommodityAddResponse": {
            "type": "object",
            "properties": {
                "count": {
                    "description": "Count 新增商品数量",
                    "type": "integer"
                },
                "ids": {
                    "description": "Ids 新增商品id",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "merchantmod.CommodityDelRequest": {
            "type": "object",
            "required": [
                "id"
            ],
            "properties": {
                "id": {
                    "description": "Id 商品id",
                    "type": "string"
                }
            }
        },
        "merchantmod.CommodityDelResponse": {
            "type": "object"
        },
        "merchantmod.CommodityHideRequest": {
            "type": "object",
            "required": [
                "id"
            ],
            "properties": {
                "id": {
                    "description": "Id 商品id",
                    "type": "string"
                }
            }
        },
        "merchantmod.CommodityHideResponse": {
            "type": "object"
        },
        "merchantmod.CommodityListRequest": {
            "type": "object",
            "required": [
                "pageNumber",
                "pageSize"
            ],
            "properties": {
                "pageNumber": {
                    "description": "Limit (min 1)",
                    "type": "integer",
                    "minimum": 1
                },
                "pageSize": {
                    "description": "Limit (min 1,max 20)",
                    "type": "integer",
                    "maximum": 20,
                    "minimum": 1
                }
            }
        },
        "merchantmod.CommodityListResponse": {
            "type": "object",
            "properties": {
                "allTags": {
                    "description": "AllTags 商户设置的所有标签",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/merchantmod.Tag"
                    }
                },
                "hasNext": {
                    "description": "HasNext true: 有下一页，否则没有下一页",
                    "type": "boolean"
                },
                "list": {
                    "description": "List 商品列表",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/merchantmod.Commodity"
                    }
                }
            }
        },
        "merchantmod.CommodityModifyRequest": {
            "type": "object",
            "required": [
                "id"
            ],
            "properties": {
                "id": {
                    "description": "Id 商品id",
                    "type": "string"
                },
                "name": {
                    "description": "PicURL 商品名称",
                    "type": "string"
                },
                "picURL": {
                    "description": "PicURL 商品缩略图",
                    "type": "string"
                },
                "tags": {
                    "description": "Tags 重设的标签列表, 仅设置selected:true 的标签\nexample: [{\"id\":\"id\",\"selected\":true}]",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/merchantmod.Tag"
                    }
                }
            }
        },
        "merchantmod.CommodityModifyResponse": {
            "type": "object",
            "properties": {
                "id": {
                    "description": "Id 商品id",
                    "type": "string"
                }
            }
        },
        "merchantmod.CommodityPublishRequest": {
            "type": "object",
            "required": [
                "id"
            ],
            "properties": {
                "id": {
                    "description": "Id 商品id",
                    "type": "string"
                }
            }
        },
        "merchantmod.CommodityPublishResponse": {
            "type": "object"
        },
        "merchantmod.FileStatusRequest": {
            "type": "object",
            "required": [
                "taskId"
            ],
            "properties": {
                "taskId": {
                    "description": "TaskId 上传任务ID",
                    "type": "string"
                }
            }
        },
        "merchantmod.FileStatusResponse": {
            "type": "object",
            "properties": {
                "status": {
                    "description": "文件和上传状态的映射",
                    "type": "object",
                    "additionalProperties": {
                        "$ref": "#/definitions/merchantmod.UploadStatus"
                    }
                },
                "taskId": {
                    "description": "TaskId 上传任务ID",
                    "type": "string"
                }
            }
        },
        "merchantmod.FileUploadResponse": {
            "type": "object",
            "properties": {
                "taskId": {
                    "description": "TaskId 上传任务ID",
                    "type": "string"
                }
            }
        },
        "merchantmod.LoginRequest": {
            "type": "object",
            "required": [
                "name",
                "password"
            ],
            "properties": {
                "name": {
                    "description": "Name 商户登录账号",
                    "type": "string"
                },
                "password": {
                    "description": "Password 商户登录密码",
                    "type": "string"
                }
            }
        },
        "merchantmod.LoginResponse": {
            "type": "object",
            "properties": {
                "category": {
                    "description": "Category 1:餐饮,2:服饰",
                    "type": "integer",
                    "enum": [
                        1,
                        2
                    ]
                },
                "name": {
                    "description": "Name 商户登录账号",
                    "type": "string"
                },
                "prtrait": {
                    "description": "Name 商户头像",
                    "type": "string"
                }
            }
        },
        "merchantmod.LogoutRequest": {
            "type": "object"
        },
        "merchantmod.LogoutResponse": {
            "type": "object"
        },
        "merchantmod.RegisterRequest": {
            "type": "object",
            "required": [
                "category",
                "name",
                "password",
                "passwordTwo",
                "tgId",
                "tgName",
                "verifyCode"
            ],
            "properties": {
                "category": {
                    "description": "Category 1:餐饮,2:服饰",
                    "type": "integer",
                    "enum": [
                        1,
                        2
                    ]
                },
                "name": {
                    "description": "Name 商户登录账号",
                    "type": "string"
                },
                "password": {
                    "description": "Password 商户登录密码",
                    "type": "string"
                },
                "passwordTwo": {
                    "description": "PasswordTwo 二次输入密码，必须和Password 一致",
                    "type": "string"
                },
                "tgId": {
                    "description": "TgID telegram 用户id",
                    "type": "integer"
                },
                "tgName": {
                    "description": "TgName telegram 用户账号",
                    "type": "string"
                },
                "tgPrtrait": {
                    "description": "TgPrtrait telegram 用户头像",
                    "type": "string"
                },
                "verifyCode": {
                    "description": "VerifyCode 验证码 从telegram获取",
                    "type": "string"
                }
            }
        },
        "merchantmod.RegisterResponse": {
            "type": "object",
            "properties": {
                "category": {
                    "description": "Category 1:餐饮,2:服饰",
                    "type": "integer",
                    "enum": [
                        1,
                        2
                    ]
                },
                "id": {
                    "description": "ID 商户id",
                    "type": "string"
                },
                "name": {
                    "description": "Name 商户登录账号",
                    "type": "string"
                },
                "prtrait": {
                    "description": "Name 商户头像",
                    "type": "string"
                }
            }
        },
        "merchantmod.SP": {
            "type": "object",
            "required": [
                "pricing",
                "specifications"
            ],
            "properties": {
                "id": {
                    "description": "Id 规格和定价id",
                    "type": "string"
                },
                "picUrl": {
                    "description": "PicURL 规格和价格缩略图",
                    "type": "string"
                },
                "pricing": {
                    "description": "Pricing 商品定价\nexample: 10，10.5",
                    "type": "number"
                },
                "specifications": {
                    "description": "Specifications 商品规格\nexample: 一个，一份，一碗，一件",
                    "type": "string"
                }
            }
        },
        "merchantmod.SPAddRequest": {
            "type": "object",
            "required": [
                "commodityId",
                "pricing",
                "specifications"
            ],
            "properties": {
                "commodityId": {
                    "description": "CommodityId 商品id",
                    "type": "string"
                },
                "picUrl": {
                    "description": "PicURL 规格与定价缩略图",
                    "type": "string"
                },
                "pricing": {
                    "description": "Pricing 商品定价",
                    "type": "number"
                },
                "specifications": {
                    "description": "Specifications 商品规格",
                    "type": "string"
                }
            }
        },
        "merchantmod.SPAddResponse": {
            "type": "object",
            "properties": {
                "id": {
                    "description": "Id 规格与定价id",
                    "type": "string"
                }
            }
        },
        "merchantmod.SPDelRequest": {
            "type": "object",
            "required": [
                "id"
            ],
            "properties": {
                "id": {
                    "description": "Id 规格与定价id",
                    "type": "string"
                }
            }
        },
        "merchantmod.SPDelResponse": {
            "type": "object"
        },
        "merchantmod.SPModifyRequest": {
            "type": "object",
            "required": [
                "id",
                "pricing",
                "specifications"
            ],
            "properties": {
                "id": {
                    "description": "Id 规格与定价id",
                    "type": "string"
                },
                "picUrl": {
                    "description": "PicURL 规格与定价缩略图",
                    "type": "string"
                },
                "pricing": {
                    "description": "Pricing 商品定价",
                    "type": "number"
                },
                "specifications": {
                    "description": "Specifications 商品规格",
                    "type": "string"
                }
            }
        },
        "merchantmod.SPModifyResponse": {
            "type": "object",
            "properties": {
                "id": {
                    "description": "Id 规格与定价id",
                    "type": "string"
                }
            }
        },
        "merchantmod.SendCodeRequest": {
            "type": "object",
            "required": [
                "name"
            ],
            "properties": {
                "name": {
                    "description": "Name 账号",
                    "type": "string"
                },
                "tgId": {
                    "description": "Telegram 用户 id",
                    "type": "integer"
                }
            }
        },
        "merchantmod.SendCodeResponse": {
            "type": "object",
            "properties": {
                "verifyCode": {
                    "description": "VerifyCode 验证码",
                    "type": "string"
                }
            }
        },
        "merchantmod.Tag": {
            "type": "object",
            "properties": {
                "id": {
                    "description": "ID 标签id",
                    "type": "string"
                },
                "name": {
                    "description": "Name 标签名",
                    "type": "string"
                },
                "selected": {
                    "description": "Selected true:已选择，否则未选择",
                    "type": "boolean"
                }
            }
        },
        "merchantmod.TagAddRequest": {
            "type": "object",
            "required": [
                "name"
            ],
            "properties": {
                "name": {
                    "type": "string"
                }
            }
        },
        "merchantmod.TagAddResponse": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                }
            }
        },
        "merchantmod.TagDelRequest": {
            "type": "object",
            "required": [
                "id"
            ],
            "properties": {
                "id": {
                    "type": "string"
                }
            }
        },
        "merchantmod.TagDelResponse": {
            "type": "object"
        },
        "merchantmod.UploadStatus": {
            "type": "object",
            "properties": {
                "at": {
                    "description": "状态更新的时间，UnixNano时间戳",
                    "type": "integer"
                },
                "consumedBytes": {
                    "description": "已经上传的尺寸",
                    "type": "integer"
                },
                "err": {
                    "description": "上传的错误信息",
                    "type": "string"
                },
                "fileName": {
                    "description": "文件名",
                    "type": "string"
                },
                "isCompleted": {
                    "description": "true: 上传完成",
                    "type": "boolean"
                },
                "rwBytes": {
                    "description": "每次写入的大小",
                    "type": "integer"
                },
                "taskId": {
                    "description": "TaskId 上传任务ID",
                    "type": "string"
                },
                "totalBytes": {
                    "description": "文件总尺寸",
                    "type": "integer"
                },
                "url": {
                    "description": "上传后获取的文件URL",
                    "type": "string"
                }
            }
        },
        "response.HTTPResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "description": "数据"
                },
                "message": {
                    "description": "信息",
                    "type": "string"
                },
                "status": {
                    "description": "| 业务响应码 | 响应信息 | 描述 |\n| ---------- | -------- | ---- |\n| 1000           | Invalid Param         | 无效参数 |\n| 2000           | Internal Server Error         | 服务器内部错误 |\n| 3000           | Tip         | 弹出信息  [查看示例](https://nutui.jd.com/#/zh-cn/component/notify)   |\n| 4000           | Reload         | 重新加载页面 |\n| 5000           | Relogin         | 重新登陆 |\n| 6000           | Redirect         | 重定向  |",
                    "type": "integer",
                    "enum": [
                        1000,
                        2000,
                        3000,
                        4000,
                        5000,
                        6000
                    ]
                }
            }
        }
    },
    "securityDefinitions": {
        "Auth": {
            "type": "apiKey",
            "name": "hoken",
            "in": "header"
        }
    }
}`

// SwaggerInfomv1 holds exported Swagger Info so clients can modify it
var SwaggerInfomv1 = &swag.Spec{
	Version:          "1.0",
	Host:             "swagger.mik888.com",
	BasePath:         "/api/merchant/v1",
	Schemes:          []string{},
	Title:            "HaiXian 商户端 API",
	Description:      "",
	InfoInstanceName: "mv1",
	SwaggerTemplate:  docTemplatemv1,
}

func init() {
	swag.Register(SwaggerInfomv1.InstanceName(), SwaggerInfomv1)
}
