basePath: /v1/user
definitions:
  response.HTTPResponse:
    properties:
      data: {}
      message:
        type: string
      status:
        type: integer
    type: object
  usermod.Commodity:
    properties:
      commodityID:
        type: string
      picURL:
        type: string
      tags:
        items:
          $ref: '#/definitions/usermod.Tags'
        type: array
    type: object
  usermod.HomeListRequest:
    properties:
      pageNumber:
        description: 当前页
        minimum: 1
        type: integer
      pageSize:
        description: 每页条数
        maximum: 20
        minimum: 1
        type: integer
    required:
    - pageNumber
    - pageSize
    type: object
  usermod.HomeListResponse:
    properties:
      hasNext:
        type: boolean
      list:
        items:
          $ref: '#/definitions/usermod.Commodity'
        type: array
    type: object
  usermod.Tags:
    properties:
      tagID:
        type: string
      tagName:
        type: string
    type: object
host: localhost:7777
info:
  contact: {}
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: HaiXian API
  version: "1.0"
paths:
  /v1/user/home/list/{xx_merchant}:
    post:
      consumes:
      - application/json
      description: 首页核心接口，展示商品列表
      parameters:
      - description: 参数
        in: body
        name: param
        required: true
        schema:
          $ref: '#/definitions/usermod.HomeListRequest'
      produces:
      - application/json
      responses:
        "200":
          description: 商品列表
          schema:
            allOf:
            - $ref: '#/definitions/response.HTTPResponse'
            - properties:
                Data:
                  $ref: '#/definitions/usermod.HomeListResponse'
              type: object
        "400":
          description: 参数错误
          schema:
            $ref: '#/definitions/response.HTTPResponse'
        "500":
          description: 内部错误
          schema:
            $ref: '#/definitions/response.HTTPResponse'
      summary: 商品列表
      tags:
      - 用户-首页
swagger: "2.0"
