// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplateuv1 = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {},
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/home/list": {
            "post": {
                "description": "首页核心接口，展示商品列表",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户-首页"
                ],
                "summary": "商品列表",
                "parameters": [
                    {
                        "description": "参数",
                        "name": "param",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/usermod.HomeListRequest"
                        }
                    },
                    {
                        "type": "string",
                        "default": "default",
                        "description": "Merchant Name",
                        "name": "merchant",
                        "in": "header"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.HTTPResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "Data": {
                                            "$ref": "#/definitions/usermod.HomeListResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "请求失败",
                        "schema": {
                            "$ref": "#/definitions/response.HTTPResponse"
                        }
                    }
                }
            }
        },
        "/home/order/submit": {
            "post": {
                "description": "提交并审核订单，为有效订单提供缩略图，为无效订单提供失效信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户-提交订单"
                ],
                "summary": "提交订单",
                "parameters": [
                    {
                        "description": "参数",
                        "name": "param",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/usermod.SubmitOrderRequest"
                        }
                    },
                    {
                        "type": "string",
                        "default": "default",
                        "description": "Merchant Name",
                        "name": "merchant",
                        "in": "header"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.HTTPResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "Data": {
                                            "$ref": "#/definitions/usermod.SubmitOrderResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "请求失败",
                        "schema": {
                            "$ref": "#/definitions/response.HTTPResponse"
                        }
                    }
                }
            }
        },
        "/home/search": {
            "post": {
                "description": "搜索商品",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户-搜索商品"
                ],
                "summary": "搜索商品",
                "parameters": [
                    {
                        "description": "参数",
                        "name": "param",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/usermod.HomeSearchRequest"
                        }
                    },
                    {
                        "type": "string",
                        "default": "default",
                        "description": "Merchant Name",
                        "name": "merchant",
                        "in": "header"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.HTTPResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "Data": {
                                            "$ref": "#/definitions/usermod.HomeSearchResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "请求失败",
                        "schema": {
                            "$ref": "#/definitions/response.HTTPResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "response.HTTPResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "description": "数据"
                },
                "message": {
                    "description": "信息",
                    "type": "string"
                },
                "status": {
                    "description": "Status 1000: Invalid Param,\nStatus 2000: Internal Server Error\nStatus 3000: Tip\nStatus 4000: Reload\nStatus 5000: Relogin\nStatus 6000: Redirect",
                    "type": "integer",
                    "enum": [
                        1000,
                        2000,
                        3000,
                        4000,
                        5000,
                        6000
                    ]
                }
            }
        },
        "usermod.Commodity": {
            "type": "object",
            "properties": {
                "category": {
                    "description": "Category 1:餐饮,2:服饰",
                    "type": "integer",
                    "enum": [
                        1,
                        2
                    ]
                },
                "count": {
                    "description": "Count 商品数量",
                    "type": "integer"
                },
                "createdAt": {
                    "description": "CreatedAt 商品创建时间",
                    "type": "string"
                },
                "id": {
                    "description": "ID 商品id",
                    "type": "string"
                },
                "invaild": {
                    "description": "Invaild true: 无效,不可选。否则可选",
                    "type": "boolean"
                },
                "invaildMsg": {
                    "description": "InvaildMsg 失效信息",
                    "type": "string"
                },
                "name": {
                    "description": "Name 商品名称",
                    "type": "string"
                },
                "online": {
                    "description": "Online 1:Online,2:Offline",
                    "type": "integer",
                    "enum": [
                        0,
                        1
                    ]
                },
                "picUrl": {
                    "description": "Name 商品缩略图",
                    "type": "string"
                },
                "show": {
                    "description": "Show 3:Show,4:Hide",
                    "type": "integer",
                    "enum": [
                        2,
                        3
                    ]
                },
                "sps": {
                    "description": "SPs 商品规格与定价,至少有一项",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/usermod.SP"
                    }
                },
                "tags": {
                    "description": "Tags 商品标签",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/usermod.Tag"
                    }
                },
                "weight": {
                    "description": "Weight 权重，控制显示顺序 desc",
                    "type": "integer"
                }
            }
        },
        "usermod.HomeListRequest": {
            "type": "object",
            "required": [
                "pageNumber",
                "pageSize"
            ],
            "properties": {
                "pageNumber": {
                    "description": "Limit (min 1)",
                    "type": "integer",
                    "minimum": 1
                },
                "pageSize": {
                    "description": "Limit (min 1,max 20)",
                    "type": "integer",
                    "maximum": 20,
                    "minimum": 1
                }
            }
        },
        "usermod.HomeListResponse": {
            "type": "object",
            "properties": {
                "hasNext": {
                    "description": "HasNext true: 有下一页，否则没有下一页",
                    "type": "boolean"
                },
                "list": {
                    "description": "List 商品列表",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/usermod.Commodity"
                    }
                }
            }
        },
        "usermod.HomeSearchRequest": {
            "type": "object",
            "required": [
                "pageNumber",
                "pageSize"
            ],
            "properties": {
                "commodityIDs": {
                    "description": "CommodityIDs 商品id",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "pageNumber": {
                    "description": "Limit (min 1)",
                    "type": "integer",
                    "minimum": 1
                },
                "pageSize": {
                    "description": "Limit (min 1,max 20)",
                    "type": "integer",
                    "maximum": 20,
                    "minimum": 1
                },
                "tagIDs": {
                    "description": "TagIDs 标签id",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "usermod.HomeSearchResponse": {
            "type": "object",
            "properties": {
                "hasNext": {
                    "description": "HasNext true: 有下一页，否则没有下一页",
                    "type": "boolean"
                },
                "list": {
                    "description": "List 商品列表",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/usermod.Commodity"
                    }
                }
            }
        },
        "usermod.SP": {
            "type": "object",
            "required": [
                "buyCount",
                "pricing",
                "specifications",
                "totalPricing"
            ],
            "properties": {
                "buyCount": {
                    "description": "BuyCount 购买数量",
                    "type": "number"
                },
                "id": {
                    "description": "Id 规格和定价id",
                    "type": "string"
                },
                "md5": {
                    "description": "MD5 规格和定价的指纹",
                    "type": "string"
                },
                "picUrl": {
                    "description": "PicURL 规格和价格缩略图",
                    "type": "string"
                },
                "pricing": {
                    "description": "Pricing 商品定价\nexample: 10，10.5",
                    "type": "number"
                },
                "selected": {
                    "description": "Selected true: 已选，否则：未选",
                    "type": "boolean"
                },
                "specifications": {
                    "description": "Specifications 商品规格\nexample: 一个，一份，一碗，一件",
                    "type": "string"
                },
                "totalPricing": {
                    "description": "TotalPricing 商品总价\nexample: TotalPricing = Pricing * BuyCount",
                    "type": "number"
                }
            }
        },
        "usermod.SubmitOrderRequest": {
            "type": "object",
            "properties": {
                "commoditys": {
                    "description": "Commoditys 商品",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/usermod.Commodity"
                    }
                },
                "totalPrice": {
                    "description": "TotalPrice 总价",
                    "type": "number"
                }
            }
        },
        "usermod.SubmitOrderResponse": {
            "type": "object",
            "properties": {
                "commoditys": {
                    "description": "Commoditys 商品",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/usermod.Commodity"
                    }
                },
                "invaild": {
                    "description": "Invaild true: 无效,不显示订单图。否则显示",
                    "type": "boolean"
                },
                "invaildMsg": {
                    "description": "InvaildMsg 失效信息",
                    "type": "string"
                },
                "jumpUrl": {
                    "description": "JumpUrl 跳转连接",
                    "type": "string"
                },
                "orderId": {
                    "description": "OrderId 订单id",
                    "type": "string"
                },
                "orderPicBuffer": {
                    "description": "OrderPicBuffer 订单缩略图",
                    "type": "string"
                },
                "totalPrice": {
                    "description": "TotalPrice 总价",
                    "type": "number"
                }
            }
        },
        "usermod.Tag": {
            "type": "object",
            "properties": {
                "id": {
                    "description": "ID 标签id",
                    "type": "string"
                },
                "name": {
                    "description": "Name 标签名",
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfouv1 holds exported Swagger Info so clients can modify it
var SwaggerInfouv1 = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:7777",
	BasePath:         "/v1/user",
	Schemes:          []string{},
	Title:            "HaiXian 用户端 API",
	Description:      "",
	InfoInstanceName: "uv1",
	SwaggerTemplate:  docTemplateuv1,
}

func init() {
	swag.Register(SwaggerInfouv1.InstanceName(), SwaggerInfouv1)
}
