basePath: /api/user/v1
definitions:
  response.HTTPResponse:
    properties:
      data:
        description: 数据
      message:
        description: 信息
        type: string
      status:
        description: |-
          | 业务响应码 | 响应信息 | 描述 |
          | ---------- | -------- | ---- |
          | 1000           | Invalid Param         | 无效参数 |
          | 2000           | Internal Server Error         | 服务器内部错误 |
          | 3000           | Tip         | 弹出信息  [查看示例](https://nutui.jd.com/#/zh-cn/component/notify)   |
          | 4000           | Reload         | 重新加载页面 |
          | 5000           | Relogin         | 重新登陆 |
          | 6000           | Redirect         | 重定向  |
        enum:
        - 1000
        - 2000
        - 3000
        - 4000
        - 5000
        - 6000
        type: integer
    type: object
  usermod.Commodity:
    properties:
      category:
        description: Category 1:餐饮,2:服饰
        enum:
        - 1
        - 2
        type: integer
      count:
        description: Count 商品数量
        type: integer
      createdAt:
        description: CreatedAt 商品创建时间
        type: string
      id:
        description: ID 商品id
        type: string
      invaild:
        description: 'Invaild true: 无效,不可选。否则可选'
        type: boolean
      invaildMsg:
        description: InvaildMsg 失效信息
        type: string
      name:
        description: Name 商品名称
        type: string
      online:
        description: Online 1:Online,2:Offline
        enum:
        - 0
        - 1
        type: integer
      picUrl:
        description: Name 商品缩略图
        type: string
      show:
        description: Show 3:Show,4:Hide
        enum:
        - 2
        - 3
        type: integer
      sps:
        description: SPs 商品规格与定价,至少有一项
        items:
          $ref: '#/definitions/usermod.SP'
        type: array
      tags:
        description: Tags 商品标签
        items:
          $ref: '#/definitions/usermod.Tag'
        type: array
      weight:
        description: Weight 权重，控制显示顺序 desc
        type: integer
    type: object
  usermod.HomeListRequest:
    properties:
      pageNumber:
        description: Limit (min 1)
        minimum: 1
        type: integer
      pageSize:
        description: Limit (min 1,max 20)
        maximum: 20
        minimum: 1
        type: integer
    required:
    - pageNumber
    - pageSize
    type: object
  usermod.HomeListResponse:
    properties:
      hasNext:
        description: 'HasNext true: 有下一页，否则没有下一页'
        type: boolean
      list:
        description: List 商品列表
        items:
          $ref: '#/definitions/usermod.Commodity'
        type: array
    type: object
  usermod.HomeSearchRequest:
    properties:
      commodityIDs:
        description: CommodityIDs 商品id
        items:
          type: string
        type: array
      pageNumber:
        description: Limit (min 1)
        minimum: 1
        type: integer
      pageSize:
        description: Limit (min 1,max 20)
        maximum: 20
        minimum: 1
        type: integer
      tagIDs:
        description: TagIDs 标签id
        items:
          type: string
        type: array
    required:
    - pageNumber
    - pageSize
    type: object
  usermod.HomeSearchResponse:
    properties:
      hasNext:
        description: 'HasNext true: 有下一页，否则没有下一页'
        type: boolean
      list:
        description: List 商品列表
        items:
          $ref: '#/definitions/usermod.Commodity'
        type: array
    type: object
  usermod.SP:
    properties:
      buyCount:
        description: BuyCount 购买数量
        type: number
      id:
        description: Id 规格和定价id
        type: string
      md5:
        description: MD5 规格和定价的指纹
        type: string
      picUrl:
        description: PicURL 规格和价格缩略图
        type: string
      pricing:
        description: |-
          Pricing 商品定价
          example: 10，10.5
        type: number
      selected:
        description: 'Selected true: 已选，否则：未选'
        type: boolean
      specifications:
        description: |-
          Specifications 商品规格
          example: 一个，一份，一碗，一件
        type: string
      totalPricing:
        description: |-
          TotalPricing 商品总价
          example: TotalPricing = Pricing * BuyCount
        type: number
    required:
    - buyCount
    - pricing
    - specifications
    - totalPricing
    type: object
  usermod.SubmitOrderRequest:
    properties:
      commoditys:
        description: Commoditys 商品
        items:
          $ref: '#/definitions/usermod.Commodity'
        type: array
      totalPrice:
        description: TotalPrice 总价
        type: number
    type: object
  usermod.SubmitOrderResponse:
    properties:
      commoditys:
        description: Commoditys 商品
        items:
          $ref: '#/definitions/usermod.Commodity'
        type: array
      invaild:
        description: 'Invaild true: 无效,不显示订单图。否则显示'
        type: boolean
      invaildMsg:
        description: InvaildMsg 失效信息
        type: string
      jumpUrl:
        description: JumpUrl 跳转连接
        type: string
      orderId:
        description: OrderId 订单id
        type: string
      orderPicBuffer:
        description: OrderPicBuffer 订单缩略图
        type: string
      totalPrice:
        description: TotalPrice 总价
        type: number
    type: object
  usermod.Tag:
    properties:
      id:
        description: ID 标签id
        type: string
      name:
        description: Name 标签名
        type: string
    type: object
host: swagger.mik888.com
info:
  contact: {}
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: HaiXian 用户端 API
  version: "1.0"
paths:
  /home/list:
    post:
      consumes:
      - application/json
      description: 首页核心接口，展示商品列表
      parameters:
      - description: 参数
        in: body
        name: param
        required: true
        schema:
          $ref: '#/definitions/usermod.HomeListRequest'
      - default: default
        description: Merchant Name
        in: header
        name: merchant
        type: string
      - default: zh-CN
        description: 语言
        in: header
        name: language
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 成功
          schema:
            allOf:
            - $ref: '#/definitions/response.HTTPResponse'
            - properties:
                Data:
                  $ref: '#/definitions/usermod.HomeListResponse'
              type: object
        "500":
          description: 请求失败
          schema:
            $ref: '#/definitions/response.HTTPResponse'
      summary: 商品列表
      tags:
      - 用户-首页
  /home/order/submit:
    post:
      consumes:
      - application/json
      description: 提交并审核订单，为有效订单提供缩略图，为无效订单提供失效信息
      parameters:
      - description: 参数
        in: body
        name: param
        required: true
        schema:
          $ref: '#/definitions/usermod.SubmitOrderRequest'
      - default: default
        description: Merchant Name
        in: header
        name: merchant
        type: string
      - default: zh-CN
        description: 语言
        in: header
        name: language
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 成功
          schema:
            allOf:
            - $ref: '#/definitions/response.HTTPResponse'
            - properties:
                Data:
                  $ref: '#/definitions/usermod.SubmitOrderResponse'
              type: object
        "500":
          description: 请求失败
          schema:
            $ref: '#/definitions/response.HTTPResponse'
      summary: 提交订单
      tags:
      - 用户-提交订单
  /home/search:
    post:
      consumes:
      - application/json
      description: 搜索商品
      parameters:
      - description: 参数
        in: body
        name: param
        required: true
        schema:
          $ref: '#/definitions/usermod.HomeSearchRequest'
      - default: default
        description: Merchant Name
        in: header
        name: merchant
        type: string
      - default: zh-CN
        description: 语言
        in: header
        name: language
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 成功
          schema:
            allOf:
            - $ref: '#/definitions/response.HTTPResponse'
            - properties:
                Data:
                  $ref: '#/definitions/usermod.HomeSearchResponse'
              type: object
        "500":
          description: 请求失败
          schema:
            $ref: '#/definitions/response.HTTPResponse'
      summary: 搜索商品
      tags:
      - 用户-搜索商品
swagger: "2.0"
